# Generated by Django 4.1.10 on 2023-08-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_address_state_alter_address_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='clients', to='register.address'),
        ),
    ]
