version: '3.9'

services:
  db:
    image: mongo
    env_file: .env
    ports:
      - 27018:27017
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.runCommand({ connectionStatus: 1 })'"]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - mongodata:/data/db

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    command: sh -c "pipenv install --deploy --ignore-pipfile && python manage.py makemigrations"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: sh -c "pipenv install --deploy --ignore-pipfile && python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

volumes:
  mongodata:
